// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk52WsWsVa4dr7V-fqHyqUtrslapy3Oso',
    appId: '1:918612417044:web:fca793ea5c73396fa42501',
    messagingSenderId: '918612417044',
    projectId: 'sendeukouwaay-3c099',
    authDomain: 'sendeukouwaay-3c099.firebaseapp.com',
    storageBucket: 'sendeukouwaay-3c099.firebasestorage.app',
    measurementId: 'G-RQMDZF5MQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW9kQLXYGxsWU66bKamGwco4psgliDmks',
    appId: '1:918612417044:android:8a96ac9cf0dc727aa42501',
    messagingSenderId: '918612417044',
    projectId: 'sendeukouwaay-3c099',
    storageBucket: 'sendeukouwaay-3c099.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtwNJ6SCjzjln60HEufeVIbKNZCt-7LQ',
    appId: '1:918612417044:ios:6adf011399115f84a42501',
    messagingSenderId: '918612417044',
    projectId: 'sendeukouwaay-3c099',
    storageBucket: 'sendeukouwaay-3c099.firebasestorage.app',
    iosBundleId: 'com.example.pageAccueil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFtwNJ6SCjzjln60HEufeVIbKNZCt-7LQ',
    appId: '1:918612417044:ios:6adf011399115f84a42501',
    messagingSenderId: '918612417044',
    projectId: 'sendeukouwaay-3c099',
    storageBucket: 'sendeukouwaay-3c099.firebasestorage.app',
    iosBundleId: 'com.example.pageAccueil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk52WsWsVa4dr7V-fqHyqUtrslapy3Oso',
    appId: '1:918612417044:web:f15d46b420f15ed1a42501',
    messagingSenderId: '918612417044',
    projectId: 'sendeukouwaay-3c099',
    authDomain: 'sendeukouwaay-3c099.firebaseapp.com',
    storageBucket: 'sendeukouwaay-3c099.firebasestorage.app',
    measurementId: 'G-PRN44QZP57',
  );
}
